feat: basic support for ColorScheme-Highlight
linuxdeepin/qt5integration pull request #116
Opened 2023-01-11 10:42 UTC by BLumia

对 ColorScheme-Highlight 非常初步的支持，尽管仍未支持 ColorScheme-Background。

此 patch 可解决 breeze 主题下，文件夹图标显示为黑色的问题。

测试方式：

1. 构建插件
2. 在较新的环境下，安装并切换默认主题到 breeze（deepin v20 可能不够新，建议使用 Arch，另，下述涉及的文件对应到[这个](https://github.com/KDE/breeze-icons/blob/master/icons/places/64/folder.svg)）
3. 获取并构建 https://github.com/BLumia/qt-icon-engine-tool （方便起见提供此工具）
4. 清空图标缓存（缓存位于 `~/.cache/deepin/icons`）
5. 使用 `QT_PLUGIN_PATH=/path/to/qt5integration/bin/plugins/` 启动上面构建得到的 `iconenginelist` 程序，并在下拉中选择 “DIconProxyEngine”
6. 观察效果，颜色非黑色即正常

![图片](https://user-images.githubusercontent.com/10095765/211785743-60882cad-6437-414b-aac5-b2c1e17eeb86.png)

此 patch 已知问题：

1. 切换当前主题色时不会清除缓存，所以会看到首次生成缓存时的图标。

2023-01-13 09:50 UTC, kegechen commented
![image](https://user-images.githubusercontent.com/23466548/212289627-4bb9a7d2-db5e-4990-a91b-0f7a92d9531a.png)
貌似没有重现。 另外发现demo几个小问题
1.  target_link_libraries 里面没有指定 Qt 版本，uos上需要写 Qt5::Qml 这种 
2. qml中的信号槽 也是比较新的写法 ()=> 这个可能有些版本不支持
3. 头文件少了 `#include <QDebug>`

2023-01-13 09:54 UTC, BLumia commented
> ![image](https://user-images.githubusercontent.com/23466548/212289627-4bb9a7d2-db5e-4990-a91b-0f7a92d9531a.png) 貌似没有重现。

是 UOS 重现的吗？UOS 的 breeze-icon 版本有点低，还没在使用 ColorScheme-Highlight 吧？

> 另外发现demo几个小问题
>
> 1. target_link_libraries 里面没有指定 Qt 版本，uos上需要写 Qt5::Qml 这种
> 2. qml中的信号槽 也是比较新的写法 ()=> 这个可能有些版本不支持
> 3. 头文件少了 #include <QDebug>

测试用途的，没太注意这类问题。我随后改下 :)

2023-01-13 09:57 UTC, kegechen commented
> 

确实 里面没有 ColorScheme-Highlight 这些style属性

2023-01-13 10:00 UTC, kegechen commented
![image](https://user-images.githubusercontent.com/23466548/212292348-50b3f982-fccb-4b4e-8b1c-29372d78e48f.png)
it works !!!

2023-01-13 12:22 UTC, kegechen commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +QThreadStorage<QPair<QString, QString>> colorScheme; // <text, highlight>
用 qMap<QString, QString> // ColorScheme-Text, color 是不是就可以解决了。后续在加颜色只需要加入相应的key-color就可以了

2023-01-13 12:55 UTC, kegechen commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +        filenames[-1] = color_scheme.first; // 在dsvg插件中会为svg图标做缓存，此处是为其添加额外的缓存文件key标识，避免不同color的svg图标会命中同一个缓存文件
只要这里加上 color_scheme.second 就可以跟随高亮色变化了

2023-01-16 01:53 UTC, BLumia commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +        filenames[-1] = color_scheme.first; // 在dsvg插件中会为svg图标做缓存，此处是为其添加额外的缓存文件key标识，避免不同color的svg图标会命中同一个缓存文件
已更新相关代码。不过感觉应该还缺少手段来通知图标引擎“主题色更新了，需要重绘图标”

2023-01-16 02:25 UTC, kegechen commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +        filenames[-1] = color_scheme.first; // 在dsvg插件中会为svg图标做缓存，此处是为其添加额外的缓存文件key标识，避免不同color的svg图标会命中同一个缓存文件
主题色改变后会重绘的， xcb ==> dtkgui ==> qApp ==> ThemeChangeEvent => repaint

2023-01-16 02:27 UTC, BLumia commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +QThreadStorage<QPair<QString, QString>> colorScheme; // <text, highlight>
追加了一个新的提交来进行此修改。其中对于原有的部分做法（比如对颜色主题设置为 `#` 表示无效）我采取了直接保留和原始行为完全一致行为的方式，感觉这种部分或许有更好的做法？

2023-01-16 02:27 UTC, kegechen reviewed
+1

2023-01-28 03:29 UTC, zccrs requested changes

2023-01-28 03:29 UTC, zccrs commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.h
> +enum PALETTE_TYPE {
在Qt里，enum都是大驼峰风格的。

2023-01-28 03:46 UTC, BLumia commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.h
> +enum PALETTE_TYPE {
已更改为 `PaletteType`。

2023-01-29 01:30 UTC, zccrs approved these changes

2023-01-29 01:44 UTC, BLumia commented
/merge

2023-01-29 01:45 UTC, merged