fix: icon size multiplied by ratio twice
linuxdeepin/qt5integration pull request #122
Opened 2023-02-15 06:51 UTC by kegechen

QIcon::pixmap will scaled with ratio
use qicon.engine->pixmap instead of qicon::pixmap

Log:

2023-02-15 07:01 UTC, zccrs requested changes

2023-02-15 07:01 UTC, zccrs commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +    QPixmap pm = color_scheme == cache_color_scheme ? entryPixmap(color_entry, size, mode, state) : QPixmap();
这部分的实现代码是不是改到dtkgui里去了，还需要在这里改吗

2023-02-15 07:32 UTC, kegechen commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +    QPixmap pm = color_scheme == cache_color_scheme ? entryPixmap(color_entry, size, mode, state) : QPixmap();
dtkgui中是有部分相同代码。 不过 iconengine  插件还是在起作用。

qicon：：fromtheme 和 QDataStream &operator>> 和 operator<< 还是会从 QIconEnginePlugin 中create iconengine. 如果使用静态的iconengine 估计不太好解决这个

2023-02-15 07:44 UTC, zccrs commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +    QPixmap pm = color_scheme == cache_color_scheme ? entryPixmap(color_entry, size, mode, state) : QPixmap();
那两边都要修复。而且要考虑 qt5integration 插件的这部分删掉走dtkgui了。

2023-02-16 01:10 UTC, kegechen commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +    QPixmap pm = color_scheme == cache_color_scheme ? entryPixmap(color_entry, size, mode, state) : QPixmap();
了解。只留一个main.cpp 实现都在dktgui.这样是可以。以后修改都在dtkgui,就一份代码了。

2023-02-16 01:37 UTC, zccrs requested changes

2023-02-16 01:37 UTC, zccrs commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +static QPixmap entryPixmap (ScalableEntry *color_entry, const QSize &size, QIcon::Mode mode, QIcon::State state)
可以加上inline

2023-03-09 06:34 UTC, FeiWang1119 commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +     return color_entry ? color_entry->svgIcon.pixmap(size, mode, state) : QPixmap();
cppcheck 提示了，Either the condition 'color_entry' is redundant or there is possible null pointer dereference: color_entry.

2023-03-14 08:40 UTC, zccrs approved these changes

2023-03-15 02:58 UTC, 18202781743 commented on iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
> +    if (auto d = color_entry->svgIcon.data_ptr())
engine 需要判断nullptr么，

2023-03-30 03:33 UTC, 18202781743 approved these changes

2023-03-30 03:33 UTC, merged