chore(CI): add OBS workflows
linuxdeepin/qt5integration pull request #133
Opened 2023-03-17 07:27 UTC by tsic404

add OBS workflows and modify PKGBUILD support OBS build

log:

2023-03-17 07:27 UTC, tsic404 commented
/review @justforlxz

2023-03-17 07:27 UTC, tsic404 commented
开启Debian Sid [amd64] deepin_develop(23) [ amd64, arm64], archlinux [ amd64 ] 构建

2023-03-17 07:28 UTC, tsic404 commented
https://build.deepin.com/package/show/deepin:Develop:dde/qt5integration
qt5integration 是 native package, gbp 默认压缩为 .tar.xz, 解压后直接为路径 `pacakge`

2023-03-29 01:28 UTC, kegechen approved these changes

2023-03-29 01:33 UTC, kegechen requested changes

2023-03-29 01:33 UTC, kegechen commented on .obs/workflows.yml
> +        project: ddeepin:Develop:dde
果然这里也有写错的。幸好看了一眼 https://github.com/linuxdeepin/dde-app-services/pull/42

2023-03-29 01:45 UTC, tsic404 commented on .obs/workflows.yml
> +        project: ddeepin:Develop:dde
已更正

2023-03-29 02:19 UTC, kegechen approved these changes

2023-03-29 02:19 UTC, merged