fix: 玲珑应用托盘无法共存
linuxdeepin/qt5integration pull request #136
Opened 2023-03-28 06:12 UTC by kamiyadm

close #3649

2023-03-29 01:26 UTC, kegechen commented on platformthemeplugin/qdeepintheme.cpp
> +
QGenericUnixTheme::createPlatformSystemTrayIcon()  不是会默认走 `new QDBusTrayIcon();` 这个逻辑吗 ？

QDeepinTheme 继承自 QGenericUnixTheme ，按说不需要再把这个代码复制一份吧

2023-03-29 01:39 UTC, kamiyadm commented on platformthemeplugin/qdeepintheme.cpp
> +
默认的那个就有问题

2023-03-29 02:30 UTC, kegechen commented on platformthemeplugin/qdeepintheme.cpp
> +
对比了一下就是改了一下 `m_instanceId` 这里，因为在沙箱中应用pid都是 2 的,导致重复了缘故吧
`m_instanceId(KDEItemFormat.arg(QCoreApplication::applicationPid()).arg(++instanceCount))`
==>
` m_instanceId(KDEItemFormat.arg(generateServiceName()))`

2023-03-29 03:07 UTC, black-desk commented
他commit message没写清楚, 大概情况是这样的:

1. 托盘图标是个平台相关的实现, kde和gnome都有自己的平台相关插件;
3. deepin目前似乎是没有专门的托盘图标接口, 目前相关业务基本在使用kde的已经弃用的接口;
4. 使用kde的老接口是因为qt提供的默认的实现用了kde的接口;
5. 这套接口目前看来没有大问题, 但是其一些实现上的细节导致了应用如果跑在容器中, 托盘图标会有bug.

所以这里将qtbase中的实现抄了过来进行了一个简单的修复.

2023-03-29 03:08 UTC, black-desk requested changes

2023-03-29 03:08 UTC, black-desk commented on platformthemeplugin/qdeepintheme.cpp
> +
> 对比了一下就是改了一下 `m_instanceId` 这里，因为在沙箱中应用pid都是 2 的,导致重复了缘故吧 `m_instanceId(KDEItemFormat.arg(QCoreApplication::applicationPid()).arg(++instanceCount))` ==> ` m_instanceId(KDEItemFormat.arg(generateServiceName()))`

 是的. 但是没办法绕过它的构造函数 所以只能整个vendor了

2023-03-29 03:48 UTC, zccrs commented
> 他commit message没写清楚, 大概情况是这样的:
> 
> 1. 托盘图标是个平台相关的实现, kde和gnome都有自己的平台相关插件;
> 2. deepin目前似乎是没有专门的托盘图标接口, 目前相关业务基本在使用kde的已经弃用的接口;
> 3. 使用kde的老接口是因为qt提供的默认的实现用了kde的接口;
> 4. 这套接口目前看来没有大问题, 但是其一些实现上的细节导致了应用如果跑在容器中, 托盘图标会有bug.
> 
> 所以这里将qtbase中的实现抄了过来进行了一个简单的修复.

commit message可以更新下

2023-03-29 03:49 UTC, zccrs commented on 3rdparty/qdbustrayicon.cpp
> +        dBusConnection()->unregisterTrayIcon(reinterpret_cast<QDBusTrayIcon*>(this));
这里需要变动吗

2023-03-29 03:50 UTC, zccrs commented on 3rdparty/qdbustrayicon.cpp
> +QDeepinDBusTrayIcon::QDeepinDBusTrayIcon()
我觉得不用改它的名字，加个 namespace 好了

2023-03-29 03:52 UTC, black-desk commented on 3rdparty/qdbustrayicon.cpp
> +QDeepinDBusTrayIcon::QDeepinDBusTrayIcon()
emmm 不用和dtk的东西保持习惯上的一致么

2023-03-29 03:53 UTC, kamiyadm commented on 3rdparty/qdbustrayicon.cpp
> +        dBusConnection()->unregisterTrayIcon(reinterpret_cast<QDBusTrayIcon*>(this));
> 这里需要变动吗
实际上不应该转换类型，应该把dbusconnection这个class的逻辑也弄过来，正在改

2023-03-29 03:53 UTC, zccrs commented on 3rdparty/qdbustrayicon.cpp
> +QDeepinDBusTrayIcon::QDeepinDBusTrayIcon()
> emmm 不用和dtk的东西保持习惯上的一致么

不用，qt5integration 不算是dtk的一部分。而且这里应该以方便跟随上游为主。

2023-03-29 06:37 UTC, zccrs requested changes

2023-03-29 06:37 UTC, zccrs commented on 3rdparty/qdbusmenuconnection.cpp
>  Q_DECLARE_LOGGING_CATEGORY(qLcMenu)
这个的名字可以改一下，避免跟Qt的日志无法区分。

2023-03-29 06:37 UTC, zccrs commented on 3rdparty/qdbustrayicon.cpp
> +} // namespace thirdparty
文件以一个空行结尾

2023-03-29 06:54 UTC, kamiyadm commented on 3rdparty/qdbusmenuconnection.cpp
>  Q_DECLARE_LOGGING_CATEGORY(qLcMenu)
改成dLcMenu ?

2023-03-29 07:11 UTC, kamiyadm commented on platformthemeplugin/qdeepintheme.cpp
> +
对，就是重复了导致dbus注册不上

2023-03-29 09:59 UTC, kegechen commented on 3rdparty/qdbusmenuconnection.cpp
>  Q_DECLARE_LOGGING_CATEGORY(qLcMenu)
不是随便改的， 要在cpp声明一个

类似这样 
```
#ifdef QT_DEBUG
Q_LOGGING_CATEGORY(lcDMenu, "dtk.qpa.menu")
#else
Q_LOGGING_CATEGORY(lcDMenu, "dtk.qpa.menu", QtInfoMsg)
#endif
```

2023-03-30 03:04 UTC, kamiyadm commented on 3rdparty/qdbusmenuconnection.cpp
>  Q_DECLARE_LOGGING_CATEGORY(qLcMenu)
ok

2023-03-30 07:18 UTC, zccrs approved these changes

2023-04-03 02:18 UTC, kegechen approved these changes

2023-04-03 02:20 UTC, merged