fix: file dialog Transient_For property
linuxdeepin/qt5integration pull request #157
Opened 2023-05-06 06:04 UTC by kegechen

原来默认显示后设置 WM_TRANSIENT_FOR 属性。
在某些情况下（如窗口还未显示）失败或者被桌面覆盖了。
增加一个窗口激活后再次确认该属性
修改 connect 的类型，防止出现重复连接

Issue: https://github.com/linuxdeepin/dtk/issues/65

2023-05-06 06:18 UTC, zccrs requested changes

2023-05-06 06:18 UTC, zccrs commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +        XGetTransientForHint(QX11Info::display(), fileDlgWId, &pid);
有必要再获取判断一下吗，是不是直接设置就行了。另外也要注意下非xcb的环境。如果逻辑和203行类似，可以提取为一个函数在两个地方调用。

2023-05-06 06:29 UTC, kegechen commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +        XGetTransientForHint(QX11Info::display(), fileDlgWId, &pid);
如果已经是自己就不在设置，也可以直接设置，实现里面正常自行对比这个属性值是否相同

2023-05-06 06:35 UTC, zccrs commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +        XGetTransientForHint(QX11Info::display(), fileDlgWId, &pid);
可以把设置 TransientForHint 的设置提取为一个函数，在这个函数里判断是不是xcb平台。

2023-05-06 06:46 UTC, zccrs requested changes

2023-05-06 06:46 UTC, zccrs commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +    if (!DPlatformHandle::isDXcbPlatform())
应该无所谓是不是 dxcb，只要是X11环境都行，不是dxcb，是Qt的xcb也没问题。
另外，非X11环境下，后续的 `filedlgInterface->activateWindow();` 这些调用应该还是需要的呀

2023-05-06 06:54 UTC, kegechen commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +    if (!DPlatformHandle::isDXcbPlatform())
这个是以前的判断，保留下来的。确实应该需要的。

2023-05-06 07:04 UTC, zccrs requested changes

2023-05-06 07:04 UTC, zccrs commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +    if (!filedlgInterface || !auxiliaryWindow)
这个判断是不是不应该，因为原有的代码好像只依赖了 filedlgInterface

2023-05-06 07:06 UTC, zccrs commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +    if (!DPlatformHandle::isDXcbPlatform())
可以继续保留。不过我觉得 XSetTransientForHint 只判断是X11环境就行了（不依赖dxcb），可以在Wayland环境下试一试。

2023-05-06 09:24 UTC, kegechen commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +    if (!DPlatformHandle::isDXcbPlatform())
wayland 测试 ok

2023-05-08 01:53 UTC, zccrs approved these changes

2023-05-08 02:39 UTC, asterwyx commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +    if (!qApp->platformName().contains("xcb"))
现在这个QApplication的属性是没有用了吗

2023-05-08 02:41 UTC, zccrs commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +    if (!qApp->platformName().contains("xcb"))
这样判断的话就不需要了，因为判断的是 contains。而且原本的逻辑是判断是不是DXCB平台，实际上只需要判断是不是xcb平台即可。

2023-05-08 02:56 UTC, kegechen commented on platformthemeplugin/qdeepinfiledialoghelper.cpp
> +    if (!qApp->platformName().contains("xcb"))
这里的意思是只要是 x11（xcb） 就可以调用 setTransientForHint
_d_isDxcb 是 dtk 的属性

2023-05-08 03:04 UTC, merged