chore: delete deprecated interface about iconengine
linuxdeepin/qt5integration pull request #181
Opened 2023-07-06 08:31 UTC by FeiWang1119

1. delete plugins(builtinengine, dciiconengine, xdgiconproxyengine).
2. modify iconproxyengine to call the interface createEngine in dtkgui.

Log: delete deprecated interface about iconengine

2023-07-07 01:52 UTC, kegechen commented on iconengineplugins/diconproxyengine/main.cpp
> +    return DIconTheme::createIconEngine(iconName);
需要加上 dtkgui 版本依赖。

2023-07-07 01:54 UTC, kegechen requested changes

2023-07-07 01:54 UTC, kegechen commented on iconengineplugins/diconproxyengine/main.cpp
> +    return DIconTheme::createIconEngine(iconName);
安装最新的dtkgui 和 这个版本的dde-qt5integration 测试常见桌面应用图标是否正常显示。
切换图标主题查看图标是否正常。

2023-07-07 09:45 UTC, FeiWang1119 commented on iconengineplugins/diconproxyengine/main.cpp
> +    return DIconTheme::createIconEngine(iconName);
依赖已经加上

2023-07-07 09:45 UTC, FeiWang1119 commented on iconengineplugins/diconproxyengine/main.cpp
> +    return DIconTheme::createIconEngine(iconName);
测试正常

2023-07-11 01:27 UTC, 18202781743 approved these changes

2023-07-18 01:45 UTC, kegechen approved these changes

2023-07-18 01:46 UTC, merged