feat: scrollbar show policy tweak
linuxdeepin/qt5integration pull request #194
Opened 2023-08-29 03:14 UTC by kegechen

- 默认显示滚动条，无滚动时启动隐藏动画
- 鼠标掠过滚动条所在（整个）区域，立即显示滚动条，移开启动隐藏动画
- 鼠标悬停，按下滚动条，滚动条一直显示
- 发生滚动时滚动条立即显示

docs:473QyXLRvOSZ7r3w

2023-08-29 03:15 UTC, kegechen commented
移除一些无关代码，如滚动条不显示时鼠标消息透明等逻辑，eventfilter 之类的

2023-08-29 03:31 UTC, zccrs requested changes

2023-08-29 03:31 UTC, zccrs commented on styleplugins/chameleon/chameleonstyle.cpp
> +                bool isHoveredOrPressed = scrollBar->state.testFlag(QStyle::State_MouseOver) ||
多个地方都有这样的逻辑，提取到一个函数里调用

2023-08-29 03:31 UTC, zccrs commented on styleplugins/chameleon/chameleonstyle.cpp
> +        scrollbar->setProperty("_d_dtk_scrollbar_visible", true);
这会不会导致显示一个新窗口时，在开始时滚动条都显示了出来，然后开始播放消失动画？还是说鼠标不移动过去时不会播放消失动画？

2023-08-29 03:42 UTC, kegechen commented on styleplugins/chameleon/chameleonstyle.cpp
> +                bool isHoveredOrPressed = scrollBar->state.testFlag(QStyle::State_MouseOver) ||
done

2023-08-29 03:44 UTC, kegechen commented on styleplugins/chameleon/chameleonstyle.cpp
> +        scrollbar->setProperty("_d_dtk_scrollbar_visible", true);
时的，和产品确认过开始就先显示出来，然后慢慢隐藏

2023-08-30 05:22 UTC, zccrs approved these changes

2023-08-30 05:38 UTC, merged

2023-09-05 08:38 UTC, kegechen commented
@toberyan 滚动条逻辑有微调，文管文字预览的顶部有个 [qpaintextedit](https://github.com/linuxdeepin/dde-file-manager/blob/765fdaff92136a4d4c82316264adb0453808abfd/src/plugins/common/dfmplugin-preview/pluginpreviews/text-preview/textcontextwidget.cpp#L19C16-L19C16) 
 会显示一下滚动条才隐藏