fix: qApp set fixed font not work
linuxdeepin/qt5integration pull request #199
Opened 2023-10-20 08:43 UTC by kegechen

onFontChanged will send ApplicationFontChange event to all windows. we stop this opration if qApp set a font

sub menu ==> draw arrow icon ==> QIcon::fromtheme ==> QIconLoader ==> themeHint(SystemIconThemeName) ==> appTheme() ==> connect ==> fontNameChanged

Issue: https://github.com/linuxdeepin/dtk/issues/124

2023-10-20 08:44 UTC, kegechen commented on platformthemeplugin/qdeepintheme.cpp
> +            sysFont->resolve(QFont::NoPropertiesResolved);
如果不这么做，app_font->resolve() 是 3 （FamilyResolved | SizeResolved）

2023-11-01 03:39 UTC, zccrs commented on platformthemeplugin/qdeepintheme.cpp
> +        QGuiApplicationPrivate::app_font->resolve())
还同时判断 resolve 的原因是？

2023-11-01 05:47 UTC, zccrs approved these changes

2023-11-01 05:47 UTC, zccrs requested changes

2023-11-01 05:47 UTC, zccrs commented on platformthemeplugin/qdeepintheme.cpp
> +            fixedFont->resolve(QFont::NoPropertiesResolved);
需要适配Qt6

2023-11-06 01:33 UTC, zccrs approved these changes

2023-11-07 01:58 UTC, merged