fix: dci cannot read when setDecideFormatFromContent
linuxdeepin/qt5integration pull request #200
Opened 2023-10-26 06:58 UTC by kegechen

QImageReader::setDecideFormatFromContent(bool ignored) If ignored is set to true, QDciPlugin::create will get empty format.

2023-10-27 01:53 UTC, BLumia approved these changes

2023-10-27 05:08 UTC, zccrs requested changes

2023-10-27 05:08 UTC, zccrs commented on imageformatplugins/dci/qdciiohandler.cpp
> +        q->canRead();
`if (!q->canRead()) return false` ?

2023-11-01 03:36 UTC, zccrs approved these changes

2023-11-01 03:40 UTC, merged

2023-11-01 03:40 UTC, kegechen commented
@BLumia 合了