feat: 动效增加开关
linuxdeepin/qt5integration pull request #245
Opened 2024-10-23 05:54 UTC by Whale107

动效增加开关,通过环境变量DTK_DISABLE_ANIMATIONS和DTK_DISABLE_ANIMATION_***控制动效总开关和单个动效开关

Log: 动效增加开关

2024-10-24 02:59 UTC, kegechen commented on styleplugins/chameleon/chameleonstyle.cpp
> +#define ENABLE_ANIMATION_PROGRESSBAR (!qEnvironmentVariableIsSet("DTK_DISABLE_ANIMATION_PROGRESSBAR"))
是不是可以直接用 dstyle 里面的宏定义？ 
chameleonstyle 是从 dstyle 继承的，是可以访问到 dstyle 的头文件定义的宏的。 重复定义

2024-10-24 03:39 UTC, Whale107 commented on styleplugins/chameleon/chameleonstyle.cpp
> +#define ENABLE_ANIMATION_PROGRESSBAR (!qEnvironmentVariableIsSet("DTK_DISABLE_ANIMATION_PROGRESSBAR"))
done

2024-10-24 05:22 UTC, kegechen approved these changes

2024-10-25 06:50 UTC, kegechen requested changes
统一使用 `DGuiApplicationHelper::testAttribute(DGuiApplicationHelper::HasAnimations)`

2024-10-25 08:17 UTC, kegechen approved these changes

2024-10-25 08:18 UTC, Whale107 commented
> 统一使用 `DGuiApplicationHelper::testAttribute(DGuiApplicationHelper::HasAnimations)`

2024-10-25 09:38 UTC, merged