feat: add dciiconengine
linuxdeepin/qt5integration pull request #93
Opened 2022-11-29 06:19 UTC by kegechen

support QIcon::fromTheme find DCI icon

Log: none
Influence: none

2022-11-29 12:43 UTC, 18202781743 commented on platformthemeplugin/qdeepintheme.cpp
> -static QIconEngine *createBuiltinIconEngine(const QString &iconName)
可以添加一个createDciIconEngine(const QString &iconName)，免得改动较多

2022-11-29 13:12 UTC, 18202781743 commented on platformthemeplugin/qdeepintheme.cpp
> +    if (!DDciIcon::fromTheme(iconName).isNull())
判断的逻辑可以按照buildiniconengine的逻辑来，用engine->isNull调用engine实现的vritual_hook来，

2022-11-29 13:14 UTC, 18202781743 commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    const auto &dciIcon = DDciIcon::fromTheme(m_iconName);
这样会重复调用fromtheme吧，一个dciicon可以保存在engine里，在各个地方复用

2022-11-29 13:14 UTC, 18202781743 commented on iconengineplugins/dciiconengine/dciiconengine.h
> + * SPDX-FileCopyrightText: 2019-2022 UnionTech Software Technology Co., Ltd.
这个时间是2022开始？

2022-11-29 13:17 UTC, 18202781743 commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +            QSet<int> sizeSet(ss.begin(), ss.end());
是否可以删掉ss，只使用sizeSet

2022-11-29 13:22 UTC, 18202781743 commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    const QPalette &appPa = qApp->palette();
palette是不是需要先取device的，判断下device是不是widget

2022-11-30 01:49 UTC, kegechen commented on platformthemeplugin/qdeepintheme.cpp
> +    if (!DDciIcon::fromTheme(iconName).isNull())
engine->isNull 最终也是要通过 DDciIcon::fromTheme(iconName).isNull() 来判断所以就一步到位了～

2022-11-30 01:51 UTC, kegechen commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    const auto &dciIcon = DDciIcon::fromTheme(m_iconName);
似的，但是 fromtheme 有缓存，而且这个iconname反正是要存的。

2022-11-30 01:51 UTC, kegechen commented on iconengineplugins/dciiconengine/dciiconengine.h
> + * SPDX-FileCopyrightText: 2019-2022 UnionTech Software Technology Co., Ltd.
copy的，要改嗯

2022-11-30 01:52 UTC, kegechen commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +            QSet<int> sizeSet(ss.begin(), ss.end());
可

2022-11-30 01:59 UTC, kegechen commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    const QPalette &appPa = qApp->palette();
iconengine里面判断widget 有点奇怪

2022-11-30 02:26 UTC, zccrs requested changes

2022-11-30 02:26 UTC, zccrs commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    const auto &dciIcon = DDciIcon::fromTheme(m_iconName);
fromTheme只会缓存dci的文件path，DDciIcon 对象还是值得缓存一下的，毕竟还需要从磁盘加载文件，还要解析dci的文件内容，对于在ListView中使用时，每次绘制都调用QIcon::pixmap 还是会挺明显的。

2022-11-30 02:26 UTC, zccrs commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +                          DDciIcon::Mode(mode), pa);
同上，mode不能直接转换

2022-11-30 02:26 UTC, zccrs commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    const QPalette &appPa = qApp->palette();
是的，这里不能引入QtWidgets的依赖。不过它是个属性，可以把 device 转换为 QObject 后通过 widget->property("palette") 读取QPalette。

2022-11-30 02:26 UTC, zccrs commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    DDciIconPalette pa(painter->pen().color(), painter->brush().color(),
这俩颜色是不是搞反了。而且绘制一个 QIcon 时没人会特意设置它的pen和brush，所以这里用它的意义不大

2022-11-30 02:26 UTC, zccrs commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +                     ss.append(dciIcon.availableSizes(DDciIcon::Theme(theme), DDciIcon::Mode(mode)));
其实不用这么复杂，只考虑当前theme下的Normal状态的Sizes就行

2022-11-30 02:26 UTC, zccrs commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +#elif
#else ？

2022-11-30 02:26 UTC, zccrs commented on iconengineplugins/dciiconengine/dciiconengine.h
> +#ifndef DBUILTINICONENGINE_H
宏错了

2022-11-30 02:26 UTC, zccrs commented on iconengineplugins/dciiconengine/main.cpp
> + * SPDX-FileCopyrightText: 2019 - 2022 UnionTech Software Technology Co., Ltd.
时间

2022-11-30 02:26 UTC, zccrs commented on platformthemeplugin/qdeepintheme.cpp
> +    if (!DDciIcon::fromTheme(iconName).isNull())
用engine的isNull判断有个好处，不为空时这个engine就直接可以用了，不会导致重复的 DDciIcon::fromTheme 调用

2022-11-30 02:26 UTC, zccrs commented on platformthemeplugin/qdeepintheme.cpp
> +    if (!DDciIcon::fromTheme(iconName).isNull())
dci的查询可以放到createIconEngine的最前面

2022-11-30 02:26 UTC, zccrs commented on tests/iconengines/dciiconengine/ut_dciiconengine.cpp
> + * SPDX-FileCopyrightText: 2021 - 2022 UnionTech Software Technology Co., Ltd.
时间

2022-11-30 06:05 UTC, kegechen commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    int s = dciIcon.actualSize(qMin(size.width(), size.height()), getAppDciTheme(), DDciIcon::Mode(mode));
hover和pressed两种状态将丢失

2022-11-30 06:54 UTC, kegechen commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +    DDciIconPalette pa(painter->pen().color(), painter->brush().color(),
这里分别是前景色和背景色，取得画笔颜色和画刷颜色

2022-11-30 08:05 UTC, kegechen commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +#elif
去掉了

2022-11-30 08:24 UTC, zccrs requested changes

2022-11-30 08:24 UTC, zccrs commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +                            qMin(size.width(), size.height()), dciTheme(),
是不是应该用 qMax。大一点是可以接受的。

2022-11-30 08:28 UTC, kegechen commented on iconengineplugins/dciiconengine/dciiconengine.cpp
> +                            qMin(size.width(), size.height()), dciTheme(),
这个地方改过，想了一下至少要是在最窄的位置可以合适显示而不是截断

2022-11-30 08:32 UTC, zccrs approved these changes

2022-11-30 09:23 UTC, kegechen commented
合并了在追加一个license的commit吧

2022-11-30 09:23 UTC, merged